# Generated by Django 4.2.1 on 2023-05-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                null=True, upload_to="diary_photo", verbose_name="이미지"
            ),
        ),
    ]
