# Generated by Django 4.2.1 on 2023-05-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_post_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="image",
            new_name="photo",
        ),
    ]
