# Generated by Django 4.2.1 on 2023-05-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog_photo", verbose_name="이미지"
            ),
        ),
    ]
